### ISSUE TITLE
Fix the link to your blog post?

### ISSUE THREAD

**Issue by Naereen** [erikbern/ping#1]
Hi,
It sounds a very interesting small project, but [the link you gave](http://erikbern.com/?p=1192) (`http://erikbern.com/?p=1192`) for the corresponding blog post is dead (I guess from an update to WordPress).
Could you give (and update the `README.rst` file) the link to the actual blog post?
Thanks in advance.
Regards

**Comment by erikbern** [comment]
it's now fixed – thanks

**Comment by Naereen** [comment]
Thank you :+1: !
